name: Notify Guilded on Push or PR Merge

on:
  push:
    branches:
      - main
      - development
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest commit info
        id: commit
        run: |
          echo "msg=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Send notification to Guilded
        run: |
          cat <<EOF > payload.json
          {
            "content": "🛠️ GitHub Repo Event\n* Repo: ${{ github.repository }}\n* Event: ${{ github.event_name }}\n* Actor: ${{ github.actor }}\n* Branch: ${{ github.ref }}\n* Commit: ${{ steps.commit.outputs.sha }}\n* Commit Message: ${{ steps.commit.outputs.msg }}\n* Commit Author: ${{ steps.commit.outputs.author }}\n"
          }
          EOF

          curl -X POST -H "Content-Type: application/json" \
            -d @payload.json \
            https://media.guilded.gg/webhooks/ca13dd0e-cd96-47b2-8a3f-e4ea8334df53/D01PNRwCXIOUyuyG6w4kAAUAaGW8EIIwGoIQ2kCymsAISkKIcAuki2AycYIeEE4O2KYY8YioU02U6u2OSqyw0q
